AUTH_USER_MODEL = 'users.User'
ACCOUNT_USER_MODEL_USER_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USER_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

LOGIN_URL = 'rest_framework:login'
LOGOUT_URL = 'rest_framework:logout'

REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'users.serializers.UserDetailSerializer'
}
