# Generated by Django 4.0.1 on 2022-02-10 02:33

from django.db import migrations, models
import users.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_biography_user_gender_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, upload_to=users.models.user.user_directory_path),
        ),
    ]
