# Generated by Django 4.0.1 on 2022-02-10 05:07

from django.db import migrations, models
import users.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to=users.models.user.user_directory_path),
        ),
    ]
